import {useMemo,useState} from 'react';
import {Heart,Shield,Swords,RotateCcw} from 'lucide-react';

type Difficulty='Easy'|'Normal'|'Hard'; type Suit='clubs'|'diamonds'|'hearts'|'spades'; type Rank='A'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'|'10'|'J'|'Q'|'K'; type Phase='DRAWING'|'CLUB_SELECTION'|'RESOLUTION'|'BATTLE_END'|'GAME_OVER';
type C={id:string;suit:Suit;rank:Rank;value:number}; type Flags=Record<Suit,boolean>;
type Summary={base:number;spade:number;total:number;heart:number;raw:number;diamond:number;counter:number;joker:boolean};
type Game={phase:Phase;difficulty:Difficulty;currentMorale:number;maximumMorale:number;enemyMorale:number;enemyLevel:number;enemyRank:Rank;attackDeck:C[];enemyDeck:C[];currentEnemy:C[];queenEnemy:C[];battleground:C[];discard:C[];removed:C[];legends:Record<Suit,C[]>;legendUsed:Flags;selected:Flags;usedClubs:string[];clubSelection:C[];jokers:number;last:string|null;duplicate:boolean;notice:string;summary:Summary|null;victory:boolean};
const SUITS:Suit[]=['clubs','diamonds','hearts','spades']; const RANKS:Rank[]=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const META={clubs:{s:'♣',n:'Clubs'},diamonds:{s:'♦',n:'Diamonds'},hearts:{s:'♥',n:'Hearts'},spades:{s:'♠',n:'Spades'}}; const MORALE={Easy:30,Normal:25,Hard:20}; const ENEMY:{[k:number]:number}={1:10,2:15,3:21,4:28,5:35,6:45,7:60,8:100};
const flags=():Flags=>({clubs:false,diamonds:false,hearts:false,spades:false});
const val=(r:Rank)=>r==='A'?1:r==='J'?11:r==='Q'?12:r==='K'?13:Number(r);
const shuffle=<T,>(a:T[])=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const deck=()=>RANKS.flatMap(rank=>SUITS.map(suit=>({id:`${rank}-${suit}`,rank,suit,value:val(rank)})));
const dups=(a:C[])=>{const m=new Map<Rank,number>();a.forEach(c=>m.set(c.rank,(m.get(c.rank)||0)+1));return [...m].filter(x=>x[1]>1).map(x=>x[0])};
function fresh(d:Difficulty):Game{const all=deck(), atk=new Set<Rank>(['A','2','3','4']);return{phase:'DRAWING',difficulty:d,currentMorale:MORALE[d],maximumMorale:MORALE[d],enemyMorale:10,enemyLevel:1,enemyRank:'5',attackDeck:shuffle(all.filter(c=>atk.has(c.rank))),enemyDeck:all.filter(c=>!atk.has(c.rank)&&c.rank!=='5').sort((a,b)=>a.value-b.value),currentEnemy:shuffle(all.filter(c=>c.rank==='5')),queenEnemy:[],battleground:[],discard:[],removed:[],legends:{clubs:[],diamonds:[],hearts:[],spades:[]},legendUsed:flags(),selected:flags(),usedClubs:[],clubSelection:[],jokers:2,last:null,duplicate:false,notice:'The first battle is ready. Draw the first Attack card.',summary:null,victory:false}}
function CardView({c,small=false,last=false,onClick}:{c:C;small?:boolean;last?:boolean;onClick?:()=>void}){return <button className={`card ${small?'small':''} ${last?'last':''}`} onClick={onClick} disabled={!onClick}><b>{c.rank}</b><strong>{META[c.suit].s}</strong><b>{c.rank}</b></button>}
function Stack({n,label}:{n:number;label:string}){return <div className="stackBox"><div className="stack"><span>{n}</span></div><small>{label}</small></div>}
function Modal({children}:{children:React.ReactNode}){return <div className="overlay"><div className="modal">{children}</div></div>}
export default function App(){const [difficulty,setDifficulty]=useState<Difficulty>('Normal');const [g,setG]=useState<Game|null>(null);const [reset,setReset]=useState(false);const [clubWarn,setClubWarn]=useState<string|null>(null);
 const active=g?.currentEnemy[0],queen=g?.queenEnemy[0]; const activeSuits=useMemo(()=>[active?.suit,queen?.suit].filter(Boolean) as Suit[],[active,queen]); const blocked=(s:Suit,legend=false)=>activeSuits.includes(s)&&!(legend&&g?.difficulty==='Easy');
 if(!g)return <main className="menu"><h1>One More Card?!</h1><p>Interactive campaign prototype</p><div className="difficulty">{(['Easy','Normal','Hard'] as Difficulty[]).map(d=><button className={difficulty===d?'chosen':''} onClick={()=>setDifficulty(d)}><b>{d}</b><span>{MORALE[d]} Morale</span></button>)}</div><button className="primary" onClick={()=>setG(fresh(difficulty))}>Start {difficulty} Game</button></main>;
 const loseMorale=(x:Game,n:number)=>{let current=x.currentMorale-n,j=x.jokers,used=false;if(current<1&&j>0){j--;current=x.maximumMorale;used=true}return[{...x,currentMorale:current,jokers:j},current<1,used] as const};
 const prepare=(x:Game)=>{let y={...x,attackDeck:[...x.attackDeck],discard:[...x.discard]};if(!y.attackDeck.length){if(!y.discard.length)return [{...y,phase:'GAME_OVER' as Phase,notice:'No drawable card exists.',victory:false},null] as const;y.attackDeck=shuffle(y.discard);y.discard=[];if(y.difficulty!=='Hard')y.currentMorale=Math.min(y.maximumMorale,y.currentMorale+y.enemyLevel)}return [y,y.attackDeck.pop()||null] as const};
 const enter=(x:Game,c:C)=>{const bg=[...x.battleground,c],duplicate=dups(bg).length>0;return{...x,battleground:bg,last:c.id,duplicate,phase:duplicate?'RESOLUTION' as Phase:'DRAWING' as Phase,notice:duplicate?`Duplicate ${dups(bg).join(', ')} detected. Base Power is 0.`:`${c.rank}${META[c.suit].s} entered the Battleground.`}};
 const draw=()=>{const [x,c]=prepare(g);setG(c?enter(x,c):x)}; const stop=()=>g.battleground.length&&setG({...g,phase:'RESOLUTION',selected:flags(),notice:'Choose optional Legend abilities, then resolve.'});
 const beginClub=(source:'legend'|'battle',id?:string)=>{let x={...g,usedClubs:source==='battle'&&id?[...g.usedClubs,id]:g.usedClubs,legendUsed:source==='legend'?{...g.legendUsed,clubs:true}:g.legendUsed};const [m,lost]=loseMorale(x,1);if(lost)return setG({...m,phase:'GAME_OVER',notice:'The Club cost reduced Morale below 1.',victory:false});let y=m,n=(source==='legend'?g.legends.clubs.length:g.battleground.length)+1,cs:C[]=[];for(let i=0;i<n;i++){const [z,c]=prepare(y);y=z;if(!c)break;cs.push(c)}setG({...y,phase:'CLUB_SELECTION',clubSelection:cs,notice:`Choose one of ${cs.length} cards.`})};
 const askClub=(source:'legend'|'battle',id?:string)=>g.currentMorale===1?setClubWarn(source==='legend'?'legend':id||''):beginClub(source,id);
 const chooseClub=(c:C)=>setG(enter({...g,discard:[...g.discard,...g.clubSelection.filter(x=>x.id!==c.id)],clubSelection:[]},c));
 const resolve=()=>{const last=g.battleground.find(c=>c.id===g.last);if(!last)return;const strength=g.battleground.length,count=(s:Suit)=>g.battleground.filter(c=>c.suit===s).length,base=g.duplicate?0:g.battleground.reduce((n,c)=>n+c.value,0),spade=blocked('spades')?0:count('spades')*strength,ls=g.selected.spades?g.legends.spades.length:0,heart=blocked('hearts')?0:count('hearts')*strength,lh=g.selected.hearts?g.legends.hearts.length:0,raw=last.value+g.enemyLevel,diamond=blocked('diamonds')?0:count('diamonds')*strength,ld=g.selected.diamonds?g.legends.diamonds.length:0,counter=Math.max(0,raw-diamond-ld),enemyMorale=g.enemyMorale-base-spade-ls;let x={...g,currentMorale:Math.min(g.maximumMorale,g.currentMorale+heart+lh),enemyMorale};const [m,lost,joker]=loseMorale(x,counter),summary={base,spade:spade+ls,total:base+spade+ls,heart:heart+lh,raw,diamond:diamond+ld,counter,joker};if(lost)return setG({...m,phase:'GAME_OVER',summary,notice:'Your Morale fell below 1 and no Joker remained.',victory:false});const legends={...m.legends,[last.suit]:[...m.legends[last.suit],last]},used={...m.legendUsed};SUITS.forEach(s=>{if(m.selected[s])used[s]=true});let clean={...m,legends,legendUsed:used,selected:flags(),discard:[...m.discard,...m.battleground.filter(c=>c.id!==last.id)],battleground:[],last:null,duplicate:false,usedClubs:[],summary};if(enemyMorale<=0)return setG({...clean,phase:'BATTLE_END',notice:'Enemy defeated. The final counterattack was survived.'});let ce=[...clean.currentEnemy.slice(1),clean.currentEnemy[0]],qe=clean.queenEnemy.length?[...clean.queenEnemy.slice(1),clean.queenEnemy[0]]:[];let guard=0;while(qe.length&&ce[0].suit===qe[0].suit&&guard++<qe.length)qe=[...qe.slice(1),qe[0]];setG({...clean,currentEnemy:ce,queenEnemy:qe,phase:'DRAWING',notice:`${last.rank}${META[last.suit].s} became a Legend.`})};
 const nextBattle=()=>{const max=g.maximumMorale+g.enemyLevel,cur=Math.min(max,g.currentMorale+g.enemyLevel);if(g.enemyRank==='K')return setG({...g,maximumMorale:max,currentMorale:cur,phase:'GAME_OVER',victory:true,notice:'You defeated the King.'});let ed=[...g.enemyDeck],common={maximumMorale:max,currentMorale:cur,legendUsed:flags(),selected:flags(),phase:'DRAWING' as Phase,summary:null};if(g.enemyRank==='10'){let j=shuffle(ed.splice(0,4)),q=shuffle(ed.splice(0,4)),guard=0;while(j[0].suit===q[0].suit&&guard++<4)q=[...q.slice(1),q[0]];return setG({...g,...common,discard:[...g.discard,...g.currentEnemy],enemyDeck:ed,currentEnemy:j,queenEnemy:q,enemyRank:'J',enemyLevel:7,enemyMorale:ENEMY[7],notice:'Jacks and Queens attack together.'})}if(g.enemyRank==='J'){const k=shuffle(ed.splice(0,4));return setG({...g,...common,removed:[...g.removed,...g.currentEnemy,...g.queenEnemy],enemyDeck:ed,currentEnemy:k,queenEnemy:[],enemyRank:'K',enemyLevel:8,enemyMorale:100,notice:'The final King battle begins.'})}const next=shuffle(ed.splice(0,4)),rank=next[0].rank,level=g.enemyLevel+1;setG({...g,...common,discard:[...g.discard,...g.currentEnemy],enemyDeck:ed,currentEnemy:next,queenEnemy:[],enemyRank:rank,enemyLevel:level,enemyMorale:ENEMY[level],notice:`The ${rank}s are ready.`})};
 const available=SUITS.filter(s=>s!=='clubs'&&g.legends[s].length&&!g.legendUsed[s]&&!blocked(s,true)); const base=g.duplicate?0:g.battleground.reduce((n,c)=>n+c.value,0); const battleClubs=g.battleground.filter(c=>c.suit==='clubs'&&!g.usedClubs.includes(c.id));
 return <main><header><div><h1>One More Card?! <small>{g.difficulty}</small> <em>Level {g.enemyLevel}</em></h1><p>{g.notice}</p></div><button onClick={()=>setReset(true)}><RotateCcw/> New game</button></header>
 <div className="morales"><Stat title="Current Morale" value={g.currentMorale} icon={<Heart/>}/><Stat title="Maximum Morale" value={g.maximumMorale} icon={<Shield/>}/><Stat title="Enemy Morale" value={g.enemyMorale} icon={<Swords/>}/></div>
 <section className={`phase ${g.phase.toLowerCase()}`}><div><small>Current phase</small><h2>{g.phase}</h2><p>Cards {g.battleground.length} · Base Power {base}</p>{g.phase==='RESOLUTION'&&available.length>0&&<p>{available.filter(s=>g.selected[s]).length} of {available.length} available Legend Areas were activated</p>}</div><div className="actions">{g.phase==='DRAWING'&&<><button onClick={draw}>Draw card</button><button onClick={stop} disabled={!g.battleground.length}>Stop drawing</button>{battleClubs.map(c=><button disabled={blocked('clubs')} onClick={()=>askClub('battle',c.id)}>Use {c.rank}♣</button>)}{g.legends.clubs.length>0&&!g.legendUsed.clubs&&<button disabled={blocked('clubs',true)} onClick={()=>askClub('legend')}>Use Club Legend</button>}</>}{g.phase==='RESOLUTION'&&<button onClick={resolve}>Resolve attack</button>}{g.phase==='BATTLE_END'&&<button onClick={nextBattle}>Continue campaign</button>}</div></section>
 <div className="board"><div><Area title="Legend Areas"><div className="legendGrid">{SUITS.map(s=>{const b=blocked(s,true),selectable=g.phase==='RESOLUTION'&&s!=='clubs'&&g.legends[s].length&&!g.legendUsed[s]&&!b;return <button className={`legend ${b?'blocked':''} ${g.selected[s]?'selected':''}`} disabled={!selectable} onClick={()=>setG({...g,selected:{...g.selected,[s]:!g.selected[s]}})}><h3>{META[s].s} {META[s].n}</h3><span>{g.legendUsed[s]?'Used':b?'Blocked':selectable?'Select':''}</span><div>{g.legends[s].map(c=><CardView c={c} small/>)||'Empty'}</div></button>})}</div></Area><Area title="Battleground"><div className="cards">{g.battleground.map(c=><CardView c={c} last={c.id===g.last}/>)}</div></Area>{g.phase==='CLUB_SELECTION'&&<Area title="Club Selection"><div className="cards">{g.clubSelection.map(c=><CardView c={c} onClick={()=>chooseClub(c)}/>)}</div></Area>}<Area title="Discard Pile"><div className="cards">{g.discard.map(c=><CardView c={c} small/>)}</div></Area>{g.summary&&<Area title="Last resolution"><p>Base {g.summary.base} · ♠ +{g.summary.spade} · Total {g.summary.total} · ♥ +{g.summary.heart} · Counter {g.summary.counter} · Joker {g.summary.joker?'used':'no'}</p></Area>}</div>
 <aside><div className="enemy"><div className="cards">{active&&<CardView c={active}/>} {queen&&<CardView c={queen}/>}</div><b>{queen?'Jacks & Queens':`Four ${g.enemyRank}s`}</b><div className="blockedSuits">{activeSuits.map(s=><span>{META[s].s} {META[s].n}</span>)}</div></div><div className="decks"><Stack n={g.enemyDeck.length} label="Enemy Deck"/><Stack n={g.attackDeck.length} label="Attack Deck"/></div><div className="jokers">Jokers <b>{'🃏'.repeat(g.jokers)||'–'}</b></div></aside></div>
 {g.phase==='GAME_OVER'&&<Modal><h2>{g.victory?'Congratulations, you won!':'Unfortunately, you lost.'}</h2><p>{g.victory?'You defeated the King and completed the campaign.':g.notice}</p><button className="primary" onClick={()=>setG(fresh(g.difficulty))}>Start a new game</button></Modal>}
 {reset&&<Modal><h2>Start a new game?</h2><p>The current game will be replaced.</p><div className="actions">{(['Easy','Normal','Hard'] as Difficulty[]).map(d=><button onClick={()=>{setG(fresh(d));setReset(false)}}>{d}</button>)}<button onClick={()=>setReset(false)}>Cancel</button></div></Modal>}
 {clubWarn!==null&&<Modal><h2>Use Club at 1 Morale?</h2><p>A Joker will be spent immediately if available.</p><div className="actions"><button onClick={()=>setClubWarn(null)}>Cancel</button><button onClick={()=>{const p=clubWarn;setClubWarn(null);beginClub(p==='legend'?'legend':'battle',p==='legend'?undefined:p)}}>Continue</button></div></Modal>}</main>}
function Area({title,children}:{title:string;children:React.ReactNode}){return <section className="area"><h4>{title}</h4>{children}</section>} function Stat({title,value,icon}:{title:string;value:number;icon:React.ReactNode}){return <div className="stat"><div><small>{title}</small><b>{value}</b></div>{icon}</div>}
